run_config:
  - run_name: "prototyping"
  
metrics:
  - name: recall
    origin_class:
      _target_: metrics.Recall

  - name: accuracy
    origin_class:
      _target_: metrics.Accuracy

  - name: TPR
    origin_class:
      _target_: metrics.TPR

  - name: MK
    origin_class:
      _target_: metrics.MK

  - name: f1
    origin_class:
      _target_: metrics.F1score

  - name: lrminus
    origin_class:
      _target_: metrics.LRMinus

  - name: lrplus
    origin_class:
      _target_: metrics.LRPlus

  - name: prevalence
    origin_class:
      _target_: metrics.PT

base_models:
  # - name: prototype1
  #   parameters:
  #     _target_: models.ffd_mnist.FFD_MNIST
  #     in_features: 784
  #     n_classes: 10
  #   optimizer:
  #     _target_: torch.optim.Adam
  #   criterion:
  #     _target_: torch.nn.CrossEntropyLoss

  - name: prototype1
    parameters:
      _target_: models.ProtoTest.ProtoTest
      in_features: 9
      out_features: 1028
      n_classes: 2
    optimizer:
      _target_: torch.optim.Adam
    criterion:
      _target_: torch.nn.CrossEntropyLoss

  - name: fdd1
    parameters:
      _target_: models.FFD.FFD
      in_features: 9
      n_classes: 2
    optimizer:
      _target_: torch.optim.Adam
    criterion:
      _target_: torch.nn.CrossEntropyLoss

  - name: resid-128
    parameters:
      _target_: models.Residual.Residual
      in_features: 9
      transit_size: 128
      n_classes: 2
    optimizer: 
      _target_: torch.optim.Adam
    criterion:
      _target_: torch.nn.CrossEntropyLoss

  - name: resid-264
    parameters:
      _target_: models.Residual.Residual
      in_features: 9
      transit_size: 264
      n_classes: 2
    optimizer: 
      _target_: torch.optim.Adam
    criterion:
      _target_: torch.nn.CrossEntropyLoss

