
metrics:
  - name: accuracy
    origin_class:
      _target_: metrics.accuracy.AccuracyMetric

  - name: recall
    origin_class:
      _target_: metrics.recall.RecallMetric

base_models:
  # - name: prototype1
  #   parameters:
  #     _target_: models.ffd_mnist.FFD_MNIST
  #     in_features: 784
  #     n_classes: 10
  #   optimizer:
  #     _target_: torch.optim.Adam
  #   criterion:
  #     _target_: torch.nn.CrossEntropyLoss

  - name: prototype1
    parameters:
      _target_: models.ProtoTest.ProtoTest
      in_features: 9
      out_features: 1028
      n_classes: 2
    optimizer:
      _target_: torch.optim.Adam
    criterion:
      _target_: torch.nn.CrossEntropyLoss

  # - name: prototype-50
  #   parameters:
  #     _target_: models.ProtoTest.ProtoTest
  #     in_features: 9
  #     out_features: 50
  #     n_classes: 2
  #   optimizer:
  #     _target_: torch.optim.Adam
  #   criterion:
  #     _target_: torch.nn.CrossEntropyLoss

  - name: prototype-1028
    parameters:
      _target_: models.ProtoTest.ProtoTest
      in_features: 9
      out_features: 1028
      n_classes: 2
    optimizer:
      _target_: torch.optim.Adam
    criterion:
      _target_: torch.nn.CrossEntropyLoss

  # - name: prototype-2040
  #   parameters:
  #     _target_: models.ProtoTest.ProtoTest
  #     in_features: 9
  #     out_features: 2040
  #     n_classes: 2
  #   optimizer:
  #     _target_: torch.optim.Adam
  #   criterion:
  #     _target_: torch.nn.CrossEntropyLoss

  - name: fdd1
    parameters:
      _target_: models.FFD.FFD
      in_features: 9
      n_classes: 2
    optimizer:
      _target_: torch.optim.Adam
    criterion:
      _target_: torch.nn.CrossEntropyLoss

  - name: resid-128
    parameters:
      _target_: models.Residual.Residual
      in_features: 9
      transit_size: 128
      n_classes: 2
    optimizer: 
      _target_: torch.optim.Adam
    criterion:
      _target_: torch.nn.CrossEntropyLoss

  - name: resid-264
    parameters:
      _target_: models.Residual.Residual
      in_features: 9
      transit_size: 264
      n_classes: 2
    optimizer: 
      _target_: torch.optim.Adam
    criterion:
      _target_: torch.nn.CrossEntropyLoss

  - name: resid-512
    parameters:
      _target_: models.Residual.Residual
      in_features: 9
      transit_size: 512
      n_classes: 2
    optimizer: 
      _target_: torch.optim.Adam
    criterion:
      _target_: torch.nn.CrossEntropyLoss

  - name: resid-1024
    parameters:
      _target_: models.Residual.Residual
      in_features: 9
      transit_size: 1024
      n_classes: 2
    optimizer: 
      _target_: torch.optim.Adam
    criterion:
      _target_: torch.nn.CrossEntropyLoss

  - name: resid-2048
    parameters:
      _target_: models.Residual.Residual
      in_features: 9
      transit_size: 2048
      n_classes: 2
    optimizer: 
      _target_: torch.optim.Adam
    criterion:
      _target_: torch.nn.CrossEntropyLoss

  # - name: cnn
  #   parameters:
  #     _target_: models.protoCNN.ProtoCNN
  #     n_classes: 10
  #   optimizer:
  #     _target_: torch.optim.Adam
  #   criterion:
  #     _target_: torch.nn.CrossEntropyLoss
  

